global_costmap:
  global_frame: map
  transform_tolerance: 20.0
  update_frequency: 20.0
  publish_frequency: 5.0
  width: 40.0
  height: 40.0
  resolution: 0.05
  origin_x: -20.0
  origin_y: -20.0
  rolling_window: true
  always_send_full_costmap: true